name: smsml-project
channels:
  - conda-forge
  - defaults  # Pastikan ini explicit
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - mlflow
  - shap
  - matplotlib
  - seaborn
  - pip
  - pip:
    - dagshub
    - dvc
