name: smsml-project
channels:
  - conda-forge
  - defaults  # Pastikan ini explicit
dependencies:
  - python=3.9
  - scikit-learn  # Sudah include joblib
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - mlflow
    - dagshub
    - shap
    - joblib>=1.2.0  # Tambahkan versi explicit
