name: smsml-project
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.9
  - pandas=1.5.0
  - scikit-learn=1.2.0
  - mlflow=2.3.0
  - shap=0.41.0
  - matplotlib=3.6.0
  - seaborn=0.12.0
  - pip=22.3.0
  - jq=1.6
  - pip:
      - dagshub==0.3.4
      - dvc==2.38.0
