name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./MLProject

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      
      # LANGKAH BARU UNTUK MENGATASI ERROR 
      - name: 3. Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.9'
          activate-environment: 'base' # Aktivasi lingkungan dasar conda
          
      - name: 4. Install MLflow and DagsHub
        # Menggunakan 'bash -l {0}' agar bisa mengakses conda di shell
        shell: bash -l {0} 
        run: |
          pip install mlflow dagshub jq
          
      - name: 5. Configure DagsHub/MLflow Credentials
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/idhak/SMSML_Idha_Kurniawati.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: echo "MLflow tracking URI is set."

      - name: 6. Run MLflow Project to Train Model
        id: train_run
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/idhak/SMSML_Idha_Kurniawati.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        # Menggunakan 'bash -l {0}' agar bisa mengakses conda di shell
        shell: bash -l {0}
        run: |
          # Menjalankan proyek MLflow.
          # MLflow sekarang akan bisa menemukan 'conda' dan 'activate'
          mlflow run .
          
      - name: 7. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 8. Build and Push Docker Image
        # Menggunakan 'bash -l {0}' agar bisa mengakses conda di shell
        shell: bash -l {0}
        run: |
          # Membuat nama image: username/nama-repo:versi
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest"

          # Mengambil RUN_ID dari MLflow
          RUN_ID=$(mlflow runs list --experiment-name "rf_experiment_tuning" --query "tags.mlflow.runName = 'RF_Tuned_Run'" -o json | jq -r '.[0].info.run_id')
          
          if [ -z "$RUN_ID" ]; then
            echo "Error: Could not find the MLflow Run ID. Aborting build."
            exit 1
          fi

          echo "Found Run ID: $RUN_ID"
          
          # Menggunakan MLflow untuk membangun Docker image
          mlflow models build-docker --model-uri "runs:/${RUN_ID}/rf_best_model" --name "$IMAGE_NAME"

          # Mendorong image ke Docker Hub
          docker push "$IMAGE_NAME"
          echo "✅ Docker image pushed to Docker Hub: $IMAGE_NAME"
          
      - name: 9. Log out from Docker Hub
        if: always()
        run: docker logout
