name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 3. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn joblib shap
          
      - name: 4. Configure DagsHub/MLflow Credentials
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/idhak/SMSML_Idha_Kurniawati.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: echo "MLflow tracking URI is set."

      - name: 5. Run MLflow Project to Train Model
        id: train_run
        working-directory: ./MLProject  # Pindah ke folder MLProject sebelum menjalankan
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/idhak/SMSML_Idha_Kurniawati.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: mlflow run .
          
      - name: 6. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 7. Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest"
          
          # Mengambil RUN_ID dari MLflow
          RUN_ID=$(mlflow runs list --experiment-name "rf_experiment_tuning" --query "tags.mlflow.runName = 'RF_Tuned_Run'" -o json | jq -r '.[0].info.run_id')
          
          if [ -z "$RUN_ID" ]; then
            echo "Error: Could not find the MLflow Run ID. Aborting build."
            exit 1
          fi

          echo "Found Run ID: $RUN_ID"
          
          # Membangun Docker image dari model
          mlflow models build-docker --model-uri "runs:/${RUN_ID}/rf_best_model" --name "$IMAGE_NAME"

          docker push "$IMAGE_NAME"
          echo "✅ Docker image pushed to Docker Hub: $IMAGE_NAME"
          
      - name: 8. Log out from Docker Hub
        if: always()
        run: docker logout
